status_html: ../data/p3_test_driver/status/pravega.html
result_filename: ../data/p3_test_driver/results/%(test)s_%(test_uuid)s.json
test_driver_log_filename: ../data/p3_test_driver/logs/p3_test_driver.log
ssh_user: ubuntu
ssh_host: 10.107.99.17
ssh_identity_file: /home/ubuntu/.ssh/id_rsa
kubernetes: false
docker: false
aws-ec2: false
terraform: false
ansible: false
